### ISSUE TITLE
Doesn't work with virtual smart card

### ISSUE THREAD

**Issue by ghost** [vletoux/PINSniff#1]
Hi - I've tried this on Win10 1809 with a virtual smart card, while using certutil -scinfo or runas /smartcard, but there's no APDU being captured. Any idea how to make this util more generic to capture the APDU for a VSC ? In your demo I've seen you using a physical smart card.

When running the PinSniff.exe, the only output that I have is the one below:

> Using live mode
> Monitoring active

Many thanks

**Comment by vletoux** [comment]
Are you seeing something with APDU trace ?
https://www.mysmartlogon.com/download/#APDUTrace

If yes, you have a driver signature problem. If no, the virtual smart card is avoiding the smart card reader driver stack.

**Comment by ghost** [comment]
APDUTrace works fine with the GIDS VSC after disabling driver signature enforcement, however with PINSniff I have the same result as mentioned above...

Any idea how to have this working with a VSC ?

Merci !

**Comment by vletoux** [comment]
PINSniff is a fork of APDUTrace but with less functionalities.
The driver code is exactly the same and PINSniff just does have a GUI.

You should see the filter driver in the smart card stack.
(in the hardware manager, zooming on the reader).
If you don't, you have a signature problem.

I needed the code signing certificate with kernel mode signature to be able to load the driver into Windows' kernel.
The fact that you have to disable the driver signature enforcement for APDUTrace is not OK: the driver is signed accordingly to the MS specification.

**Comment by ghost** [comment]
Hi again and thanks for the details. I confirm it works. I used the driver embedded in APDUTrace with PINSniff and the 32-bit version of the SC filter drivers (PINSniffDriver.sys) does the trick with a VSC.
Though the signing certificate used in APDUTrace's embedded driver expired last year.

![image](https://user-images.githubusercontent.com/551822/61827380-adf52e80-ae64-11e9-836a-344afdccbb6c.png)

The problem I was experiencing was due to the 64 bit version of the SC filter driver (PINSniffDriver.sys) that doesn't want to load correctly (err - "The driver \Driver\PINSniffDriver failed to load for the device ROOT\SMARTCARDREADER\0000")

Fantastic tooling ! 👍

**Comment by vletoux** [comment]
The driver signature is time stamped and then the expiration should not be a problem 
(Note: expired certificate works for quite a while for « compatibility reasons »...)
